/* Deterministic browser integration: static files and Mail fixtures in memory. */
const assert = require('node:assert/strict');
const fs = require('node:fs/promises');
const path = require('node:path');
const { chromium } = require('./.tmp/node_modules/playwright-core');
const root = path.resolve(__dirname,'../src/remnawave_manager/data/disguises/04-signal-works');
const origin = 'https://answers.test';
const rawQuestion = { id:240938818,title:'Как получить данные?',content:{type:'doc',content:[{type:'paragraph',content:[{type:'text',text:'Текст открытого вопроса'}]}]},author:{id:1,nick:'Автор Mail',avatar:''},spaces:[{title:'Программирование',path:'programming'}],created_at:'2026-09-16T10:00:00+03:00',replies_count:1 };
const rawAnswer = { id:2067147668,content:{type:'doc',content:[{type:'paragraph',content:[{type:'text',text:'Открытый ответ Mail'}]}]},author:{id:2,nick:'Ответивший'},created_at:'2026-09-16T10:10:00+03:00',reply_to:0 };
let browser;
(async()=>{
  browser=await chromium.launch({executablePath:process.env.ANSWERS_BROWSER || '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true});
  const context=await browser.newContext({locale:'ru-RU',viewport:{width:1440,height:900}});
  const errors=[],writes=[],csp=[],mailRequests=[];
  let failFeed=false,failAnswers=false,emptyAnswers=false,emptyFeed=false;
  await context.route('**/*',async(route)=>{
    const request=route.request(),url=new URL(request.url()),p=url.pathname;
    if (url.pathname.startsWith('/shared/'))
      return route.fulfill({ contentType: url.pathname.endsWith('.css') ? 'text/css' : 'text/javascript', body: await fs.readFile(path.resolve(root, '..' + url.pathname)) });
    if (url.pathname.startsWith('/_images/'))
      return route.fulfill({ contentType: 'image/svg+xml', body: '<svg xmlns="http://www.w3.org/2000/svg" width="10" height="10"><rect width="10" height="10" fill="green"/></svg>' });
    if(request.method()!=='GET'){ writes.push(`${request.method()} ${p}`); return route.fulfill({status:405,body:''}); }
    if(p.startsWith('/_answers/mail/')){
      mailRequests.push(request.url());
      let result;
      if(p==='/_answers/mail/feed') {
        if(failFeed) return route.fulfill({status:502,contentType:'application/json',body:'{"detail":"unavailable"}'});
        result={feed:emptyFeed?[]:[rawQuestion],params:{pos:null}};
      }
      else if(p==='/_answers/mail/spaces') result=[{id:1008,title:'Программирование',path:'programming'}];
      else if(p==='/_answers/mail/search') result={feed:[rawQuestion],params:null};
      else if(p==='/_answers/mail/question/240938818') result=rawQuestion;
      else if(p==='/_answers/mail/answers/240938818') {
        if(failAnswers) return route.fulfill({status:502,contentType:'application/json',body:'{"detail":"unavailable"}'});
        result={replies:emptyAnswers?[]:[rawAnswer],params:{last:2067147668,count:emptyAnswers?0:1}};
      }
      else return route.fulfill({status:404,body:'{}',contentType:'application/json'});
      return route.fulfill({status:200,contentType:'application/json; charset=utf-8',body:JSON.stringify({result})});
    }
    const file=path.resolve(root, '.'+ (p==='/'?'/index.html':p));
    if(!file.startsWith(root+path.sep)) return route.fulfill({status:404,body:''});
    try { const body=await fs.readFile(file); const type=p.endsWith('.js')?'text/javascript':p.endsWith('.css')?'text/css':p.endsWith('.svg')?'image/svg+xml':'text/html'; return route.fulfill({status:200,contentType:type,body}); } catch { return route.fulfill({status:404,body:''}); }
  });
  const page=await context.newPage();
  page.on('pageerror',(error)=>errors.push(error.message));
  page.on('console',(msg)=>{if(msg.type()==='error') errors.push(msg.text());});
  page.on('console',(msg)=>{if(msg.text().includes('Content Security Policy')) csp.push(msg.text());});
  await page.goto(origin+'/');
  await page.getByRole('heading',{name:'Как получить данные?'}).waitFor();
  assert.match(await page.locator('main').innerText(),/Автор Mail/);
  assert.equal(await page.locator('.brand-name').textContent(),'Spros','brand name must not contain a space');
  assert.equal(await page.locator('[data-action="ask"]').count(),1,'only the sidebar ask button is shown on the feed');
  assert.equal(await page.locator('.question-card [data-action="vote"][data-value="-1"]').count(),1,'preview cards show dislike');
  await page.locator('.question-card .author-link').click();
  await page.getByRole('heading',{name:'Автор Mail'}).waitFor();
  assert.equal(await page.locator('.profile-tabs .profile-tab').count(),2,'public profiles have separate questions and answers');
  assert.equal(await page.locator('.profile-page-head [data-action="back"]').count(),1,'public profiles have a visible back button');
  await page.reload();
  await page.getByRole('heading',{name:'Автор Mail'}).waitFor();
  assert.equal(await page.getByText('Профиль не найден.').count(),0,'cached external profile survives a refresh');
  await page.getByRole('button',{name:'← Назад'}).click();
  await page.getByRole('heading',{name:'Как получить данные?'}).waitFor();
  await page.locator('.question-card .author-link').click();
  await page.getByRole('heading',{name:'Автор Mail'}).waitFor();
  await page.locator('.profile-tab[href="#/user/mail/1/answers"]').click();
  await page.getByText('Здесь пока нет ответов.').waitFor();
  await page.locator('.side a[href="#/home"]').click();
  await page.getByRole('heading',{name:'Как получить данные?'}).waitFor();
  await page.locator('[data-form="search"] [name="term"]').fill('данные');
  await page.locator('[data-form="search"]').press('Enter');
  await page.getByRole('heading',{name:'Как получить данные?'}).waitFor();
  await page.getByRole('link',{name:'Как получить данные?'}).click();
  await page.getByText('Открытый ответ Mail').waitFor();
  await page.locator('.answer-card .author-link').first().click();
  await page.getByRole('heading',{name:'Ответивший'}).waitFor();
  await page.locator('.profile-tab[href="#/user/mail/2/answers"]').click();
  await page.getByText('Открытый ответ Mail').waitFor();
  await page.goBack();
  await page.goBack();
  assert.match(await page.locator('main').innerText(),/Как получить данные/);
  failAnswers=true;
  const partialPage=await context.newPage();
  await partialPage.goto(origin+'/#/question/mail/240938818');
  await partialPage.getByRole('heading',{name:'Как получить данные?'}).waitFor();
  await partialPage.getByText('Ответы пока недоступны.').waitFor();
  assert.equal(await partialPage.getByText('Не удалось загрузить данные.',{exact:true}).count(),0,'a reply failure must not hide the question');
  await partialPage.close();
  failAnswers=false;
  emptyAnswers=true;
  const emptyPage=await context.newPage();
  await emptyPage.goto(origin+'/#/question/mail/240938818');
  await emptyPage.getByText('Здесь пока нет ответов.').waitFor();
  assert.equal(await emptyPage.getByText('Ответы пока недоступны.').count(),0);
  await emptyPage.close();
  emptyAnswers=false;
  await page.locator('[data-form="answer"] textarea').fill('Черновик до входа');
  await page.locator('[data-form="answer"] .primary').click();
  await page.locator('[data-form="auth"]').waitFor();
  await page.locator('.modal button').last().focus();
  await page.keyboard.press('Tab');
  assert.equal(await page.evaluate(()=>!!document.activeElement.closest('.modal')),true,'Tab stays inside the modal');
  await page.locator('.modal button').first().focus();
  await page.keyboard.press('Shift+Tab');
  assert.equal(await page.evaluate(()=>!!document.activeElement.closest('.modal')),true,'Shift+Tab stays inside the modal');
  await page.locator('.modal [data-action="close"]').click();
  assert.equal(await page.locator('[data-form="answer"] textarea').inputValue(),'Черновик до входа');
  assert.equal(await page.locator('[data-form="answer"] textarea').evaluate(node=>node===document.activeElement),true,'closing auth returns focus to the draft');
  await page.locator('[data-form="answer"] .primary').click();
  await page.getByRole('button',{name:'Создать профиль'}).click();
  await page.locator('[data-form="auth"] [name="name"]').fill('Аня');
  await page.evaluate(async()=>{const channel=new BroadcastChannel('answers:workspace:v1');channel.postMessage('changed');channel.close();await new Promise((resolve)=>setTimeout(resolve,100));});
  assert.equal(await page.locator('[data-form="auth"] [name="name"]').inputValue(),'Аня','background updates preserve open modal fields');
  await page.locator('[data-form="auth"] [name="email"]').fill('anya@example.test');
  await page.locator('[data-form="auth"] [name="password"]').fill('password123');
  await page.locator('[data-form="auth"] .primary').click();
  await page.locator('.modal').waitFor({state:'hidden'});
  assert.equal(await page.locator('[data-form="answer"] textarea').inputValue(),'Черновик до входа','sign-in preserves the guest draft');
  await page.getByRole('button',{name:'Сохранить'}).click();
  await page.reload();
  await page.locator('.side a[href="#/saved"]').click();
  await page.getByRole('heading',{name:'Как получить данные?'}).waitFor();
  await page.goto(origin+'/#/space/programming');
  await page.getByRole('heading',{name:'Как получить данные?'}).waitFor();
  await page.getByRole('link',{name:'Как получить данные?'}).click();
  assert.equal(await page.locator('.composer').evaluate((node)=>node.nextElementSibling?.matches('.answers-title')),true,'answer form must be above the answer list');
  await page.locator('[data-form="answer"] textarea').fill('Мой локальный ответ');
  await page.locator('[data-form="answer"] [data-attachment-input]').setInputFiles([
    {name:'answer.txt',mimeType:'text/plain',buffer:Buffer.from('attached answer')},
    {name:'preview.png',mimeType:'image/png',buffer:Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVQIHWP4z8DwHwAFgAI/ScL9WQAAAABJRU5ErkJggg==','base64')},
  ]);
  await page.evaluate(async()=>{const channel=new BroadcastChannel('answers:workspace:v1');channel.postMessage('changed');channel.close();await new Promise((resolve)=>setTimeout(resolve,100));});
  assert.equal(await page.locator('[data-form="answer"] textarea').inputValue(),'Мой локальный ответ','background updates preserve answer drafts');
  assert.deepEqual(await page.locator('[data-form="answer"] [data-attachment-input]').evaluate((input)=>[...input.files].map((file)=>file.name)),['answer.txt','preview.png'],'background updates preserve selected files');
  await page.locator('[data-form="answer"] [data-attachment-selection]').getByText('answer.txt').waitFor();
  await page.locator('[data-form="answer"] .primary').click();
  await page.getByText('Мой локальный ответ').waitFor();
  assert.equal(await page.locator('[data-form="answer"] textarea').inputValue(),'','successful submission clears the draft');
  await page.getByRole('link',{name:'answer.txt'}).waitFor();
  await page.getByRole('img',{name:'preview.png'}).waitFor();
  await page.locator('.answer-card').filter({hasText:'Мой локальный ответ'}).getByRole('button',{name:'Комментарий'}).click();
  const firstReply=page.locator('.answer-card').filter({hasText:'Мой локальный ответ'}).locator('[data-form="comment"]');
  await firstReply.locator('textarea').fill('Первый комментарий');
  await firstReply.locator('[data-attachment-input]').setInputFiles({name:'comment.txt',mimeType:'text/plain',buffer:Buffer.from('attached comment')});
  await firstReply.locator('.primary').click();
  await page.getByText('Первый комментарий').waitFor();
  await page.getByRole('link',{name:'comment.txt'}).waitFor();
  await page.locator('.comment-item').filter({hasText:'Первый комментарий'}).getByRole('button',{name:'Ответить'}).click();
  const nestedReply=page.locator('.comment-item').filter({hasText:'Первый комментарий'}).locator('[data-form="comment"]');
  await nestedReply.locator('textarea').fill('Вложенный комментарий');
  await page.locator('[data-form="answer"] textarea').focus();
  assert.equal(await page.locator('[data-form="comment"]').count(),0,'focusing the main reply form must close an inline reply');
  await page.locator('.comment-item').filter({hasText:'Первый комментарий'}).getByRole('button',{name:'Ответить'}).click();
  await page.locator('.comment-item').filter({hasText:'Первый комментарий'}).locator('[data-form="comment"] textarea').fill('Вложенный комментарий');
  await page.locator('.comment-item').filter({hasText:'Первый комментарий'}).locator('[data-form="comment"] .primary').click();
  await page.getByText('Вложенный комментарий').waitFor();
  const nestedComment=page.locator('.comment-item').filter({hasText:'Вложенный комментарий'}).last();
  await nestedComment.getByRole('button',{name:'Удалить'}).click();
  await page.getByRole('heading',{name:'Удалить публикацию?'}).waitFor();
  assert.equal(await nestedComment.count(),1,'the item remains until deletion is confirmed');
  await page.locator('.modal [data-action="confirm-delete"]').click();
  await page.locator('.modal').waitFor({state:'hidden'});
  await page.getByText('Вложенный комментарий').waitFor({state:'detached'});
  assert.equal(await page.getByText('Вложенный комментарий').count(),0,'the confirmed item is removed');
  await page.goto(origin+'/#/local');
  await page.locator('main [data-action="ask"]').click();
  await page.locator('[data-form="question"] [name="title"]').fill('Как работает локальная доска?');
  await page.locator('[data-form="question"] [name="body"]').fill('Хочу узнать подробности');
  await page.locator('[data-form="question"] [data-attachment-input]').setInputFiles({name:'question.txt',mimeType:'text/plain',buffer:Buffer.from('attached question')});
  await page.locator('[data-form="question"] .primary').click();
  await page.getByRole('heading',{name:'Как работает локальная доска?'}).waitFor();
  const ownQuestionUrl = page.url();
  await page.getByText('Здесь пока нет ответов.').waitFor();
  await page.getByRole('link',{name:'question.txt'}).waitFor();
  await page.locator('[data-form="answer"] textarea').fill('Она работает в этом браузере');
  await page.locator('[data-form="answer"] .primary').click();
  await page.getByText('Она работает в этом браузере').waitFor();
  await page.getByRole('button',{name:'Выбрать лучшим'}).click();
  await page.getByText('Лучший ответ').waitFor();
  await page.reload();
  await page.getByText('Она работает в этом браузере').waitFor();
  await page.locator('[data-action="language"]').click();
  await page.getByText('Best answer').waitFor();
  await page.setViewportSize({width:360,height:780});
  assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true,'mobile overflow');
  const mobileSearch=await page.locator('.head-search').boundingBox();
  assert.ok(mobileSearch && mobileSearch.width>=300,'the mobile search field stays wide and visible');
  await page.screenshot({path:path.join(__dirname,'.tmp/answers-mobile.png'),fullPage:true});
  await page.setViewportSize({width:1440,height:900});
  await page.screenshot({path:path.join(__dirname,'.tmp/answers-desktop.png'),fullPage:true});
  await page.locator('.side a[href="#/profile"]').click();
  await page.locator('[data-action="edit-profile"]').waitFor();
  assert.equal(await page.locator('[data-action="ask"]').count(),1,'profile keeps only the sidebar ask button');
  assert.equal(await page.locator('.profile-tabs .profile-tab').count(),3,'own profile separates questions, answers and notifications');
  await page.locator('.profile-tab[href="#/profile/answers"]').click();
  await page.getByText('Она работает в этом браузере').waitFor();
  await page.locator('.profile-tab[href="#/profile/questions"]').click();
  await page.getByRole('button',{name:'Edit profile'}).click();
  await page.locator('[data-form="profile"] [name="bio"]').fill('Люблю хорошие ответы');
  await page.locator('[data-form="profile"] .primary').click();
  await page.getByText('Люблю хорошие ответы').waitFor();
  await page.reload();
  await page.getByText('Люблю хорошие ответы').waitFor();
  await page.locator('.side a[href="#/local"]').click();
  assert.equal(await page.getByRole('link',{name:'Как работает локальная доска?'}).count(),1);
  await page.locator('.side a[href="#/profile"]').click();
  await page.getByRole('button',{name:'Sign out'}).click();
  await page.getByRole('heading',{name:'Sign out of your profile?'}).waitFor();
  await page.getByRole('button',{name:'Sign out'}).last().click();
  await page.locator('.side a[href="#/local"]').click();
  await page.getByText('Sign in to continue.', { exact:true }).waitFor();
  assert.equal(await page.getByRole('link',{name:'Как работает локальная доска?'}).count(),0,'sign-out immediately locks My questions');
  await page.reload();
  await page.getByText('Sign in to continue.', { exact:true }).waitFor();
  await page.getByRole('button',{name:'Sign in'}).first().click();
  await page.getByRole('button',{name:'Create profile'}).click();
  await page.locator('[data-form="auth"] [name="name"]').fill('Борис');
  await page.locator('[data-form="auth"] [name="email"]').fill('boris@example.test');
  await page.locator('[data-form="auth"] [name="password"]').fill('password456');
  await page.locator('[data-form="auth"] .primary').click();
  await page.locator('.modal').waitFor({state:'hidden'});
  await page.locator('.side a[href="#/profile"]').click();
  await page.getByRole('button',{name:'Edit profile'}).click();
  const profilePhoto = await page.evaluate(() => {
    const canvas=document.createElement('canvas'); canvas.width=8; canvas.height=8;
    canvas.getContext('2d').fillRect(0,0,8,8);
    return canvas.toDataURL('image/png').split(',')[1];
  });
  await page.locator('[data-profile-avatar]').setInputFiles({name:'boris.png',mimeType:'image/png',buffer:Buffer.from(profilePhoto,'base64')});
  await page.locator('[data-profile-preview] img').waitFor();
  await page.locator('[data-form="profile"] .primary').click();
  await page.locator('.profile-hero img.profile-avatar').waitFor();
  await page.locator('.side a[href="#/local"]').click();
  assert.equal(await page.getByRole('link',{name:'Как работает локальная доска?'}).count(),0,'My questions excludes another account');
  await page.goto(ownQuestionUrl);
  await page.locator('[data-form="answer"] textarea').fill('Ответ второго локального профиля');
  await page.locator('[data-form="answer"] .primary').click();
  await page.getByText('Ответ второго локального профиля').waitFor();
  const otherAvatar=await page.locator('.answer-card').filter({hasText:'Ответ второго локального профиля'}).locator('.author-avatar').getAttribute('src');
  assert.equal(otherAvatar?.startsWith('data:image/jpeg;base64,'),true,'other users show their uploaded avatars');
  await page.locator('.side a[href="#/profile"]').click();
  await page.getByRole('button',{name:'Sign out'}).click();
  await page.getByRole('heading',{name:'Sign out of your profile?'}).waitFor();
  await page.getByRole('button',{name:'Sign out'}).last().click();
  await page.getByRole('button',{name:'Sign in'}).first().click();
  await page.locator('[data-form="auth"] [name="email"]').fill('anya@example.test');
  await page.locator('[data-form="auth"] [name="password"]').fill('password123');
  await page.locator('[data-form="auth"] .primary').click();
  await page.locator('.modal').waitFor({state:'hidden'});
  await page.locator('.side a[href="#/profile"]').click();
  await page.locator('.profile-tab[href="#/profile/notifications"]').click();
  await page.getByText('Борис · Answer').waitFor();
  await page.locator('.notification-copy a[href^="#/user/local/"]').click();
  await page.getByRole('heading',{name:'Борис'}).waitFor();
  await page.locator('.profile-hero img.profile-avatar').waitFor();
  await page.locator('.profile-tab[href$="/answers"]').click();
  await page.getByText('Ответ второго локального профиля').waitFor();
  await page.locator('.side a[href="#/profile"]').click();
  await page.evaluate(async()=>{
    const db=await new Promise((resolve,reject)=>{const request=indexedDB.open('answers:workspace:v1');request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error);});
    await new Promise((resolve,reject)=>{const tx=db.transaction('kv','readwrite');tx.objectStore('kv').put({accounts:null,questions:'bad',answers:[],comments:[],votes:[],saves:null,snapshots:42},'state');tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error);});
    db.close();
    localStorage.setItem('answers:feed:v1',JSON.stringify({at:Date.now(),items:[{id:'mail:1',sourceId:1,title:'bad',body:'bad',spaces:'bad',original:'https://example.test/'}]}));
  });
  await page.goto(origin+'/#/home');
  await page.reload();
  await page.getByRole('heading',{name:'Every question starts a conversation.'}).waitFor();
  assert.equal(mailRequests.some((url)=>url.includes('pos=null')),false,'null cursor leaked into request');
  assert.deepEqual(writes,[]);
  assert.deepEqual(csp,[]);
  assert.deepEqual(errors,[]);
  await page.evaluate(()=>localStorage.removeItem('answers:feed:v1'));
  failFeed=true;
  const failedPage=await context.newPage();
  await failedPage.goto(origin+'/#/home');
  await failedPage.getByText('Could not load data.',{exact:true}).waitFor();
  assert.equal(await failedPage.getByText('Could not load data.',{exact:true}).count(),1,'feed error must be rendered once');
  await failedPage.close();
  failFeed=false; emptyFeed=true;
  const emptyFeedPage=await context.newPage();
  await emptyFeedPage.goto(origin+'/#/home');
  await emptyFeedPage.getByText('No questions here yet.').waitFor();
  await emptyFeedPage.close();
  emptyFeed=false;
  rawQuestion.title='<img src=x onerror="window.__xss=1">';
  const untrustedPage=await context.newPage();
  await untrustedPage.goto(origin+'/#/home');
  await untrustedPage.locator('.question-card h3').waitFor();
  assert.equal(await untrustedPage.locator('.question-card h3 img').count(),0,'external HTML remains plain text');
  assert.equal(await untrustedPage.evaluate(()=>window.__xss),undefined);
  await untrustedPage.close();
  await page.evaluate(async()=>{
    const db=await new Promise((resolve,reject)=>{const request=indexedDB.open('answers:workspace:v1');request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error);});
    await new Promise((resolve,reject)=>{const tx=db.transaction('kv','readwrite');tx.objectStore('kv').put({accounts:[],questions:[{id:'local:x" onmouseover="window.__xss=1" z="',title:'Unsafe link',body:'',space:'',created:new Date().toISOString(),authorId:'missing'}],answers:[],comments:[],votes:{},saves:{},snapshots:{}},'state');tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error);});
    db.close();
  });
  await page.goto(origin+'/#/local');
  await page.reload();
  assert.equal(await page.getByRole('link',{name:'Unsafe link'}).count(),0,'guests cannot open My questions');
  await page.goto(origin+'/#/search/Unsafe');
  const unsafeLink=page.getByRole('link',{name:'Unsafe link'});
  await unsafeLink.waitFor();
  assert.equal(await unsafeLink.getAttribute('href'),'#/home','invalid stored IDs cannot inject link attributes');
  assert.equal(await unsafeLink.getAttribute('onmouseover'),null);
  assert.deepEqual(errors,[]);
  console.log('Answers browser scenarios passed');
})().catch((error)=>{console.error(error);process.exitCode=1;}).finally(async()=>{if(browser)await browser.close();});
